// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akumzvumderdztkakgtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrdW16dnVtZGVyZHp0a2FrZ3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTY1NzgsImV4cCI6MjA3MTM5MjU3OH0.zgyFCBOb7KNkEbIEbxmK42P_DbcDZPHbRiUjP5GNoRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});